# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-08-20 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('S_Name', models.CharField(max_length=50)),
                ('S_Roll', models.IntegerField()),
                ('S_Class', models.IntegerField()),
                ('S_Location', models.CharField(max_length=50)),
            ],
        ),
    ]
